In [1]:
# EJERCICIO 1
import numpy as np

# Crear un arreglo de números del 1 al 9 (el 10 no se incluye)
numeros = np.arange(1, 10)

# Reorganizar el arreglo en una matriz de 3x3
matriz_3x3 = numeros.reshape(3, 3)

# Imprimir la matriz resultante
print("Matriz de 3x3 con valores de 1 a 9:")
print(matriz_3x3)

Matriz de 3x3 con valores de 1 a 9:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# EJERCICIO 2
# Crear una matriz de 5 filas y 3 columnas llena de unos
# La forma se pasa como una tupla (filas, columnas)
matriz_de_unos = np.ones((5, 3))

# Imprimir la matriz resultante
print("Matriz de 5x3 formada por unos:")
print(matriz_de_unos)

Matriz de 5x3 formada por unos:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
